# Generated by Django 5.0.3 on 2024-09-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=1000)),
                ('prediction', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Bipolar', 'Bipolar'), ('Depression', 'Depression'), ('Normal', 'Normal'), ('Personality disorder', 'Personality disorder'), ('Stress', 'Stress'), ('Suicidal', 'Suicidal')], default='Normal', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anxiety_score', models.IntegerField(default=0)),
                ('bipolar_score', models.IntegerField(default=0)),
                ('depression_score', models.IntegerField(default=0)),
                ('normal_score', models.IntegerField(default=0)),
                ('personality_disorder_score', models.IntegerField(default=0)),
                ('stress_score', models.IntegerField(default=0)),
                ('suicidal_score', models.IntegerField(default=0)),
                ('help_text', models.TextField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_dash', to='dashboard.dashboard')),
            ],
        ),
    ]
