# Generated by Django 5.0.4 on 2024-09-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_alter_dashboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=1000)),
                ('prediction', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Bipolar', 'Bipolar'), ('Depression', 'Depression'), ('Normal', 'Normal'), ('Personality disorder', 'Personality disorder'), ('Stress', 'Stress'), ('Suicidal', 'Suicidal')], default='Normal', max_length=20)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_dash', to='dashboard.dashboard')),
            ],
        ),
    ]
