# Generated by Django 5.0.3 on 2024-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_alter_sentiment_anxiety_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='anxiety_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='bipolar_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='depression_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='normal_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='personality_disorder_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='stress_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='suicidal_score',
            field=models.FloatField(),
        ),
    ]
